# Sample  from a Covariance Matrix

In [1]:
import numpy as np
import scipy
import scipy.linalg
from pprint import pprint

Create a Covariance Matrix

In [3]:
n=5
rP=np.random.randn(n,n)
P=rP @ rP.T
pprint(P)

array([[ 8.22826353,  2.05848291, -1.07827421, -3.83039664,  2.44112171],
       [ 2.05848291,  1.77055549, -2.05521103, -2.31331931, -1.23092972],
       [-1.07827421, -2.05521103,  3.3726527 ,  2.45795968,  1.99007363],
       [-3.83039664, -2.31331931,  2.45795968,  5.50205099,  0.28005927],
       [ 2.44112171, -1.23092972,  1.99007363,  0.28005927,  4.548449  ]])


Generate Samples from P

In [4]:
L = scipy.linalg.cholesky(P).T
pprint(L)

array([[ 2.86849499,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.71761775,  1.12052678,  0.        ,  0.        ,  0.        ],
       [-0.37590242, -1.5934084 ,  0.83210561,  0.        ,  0.        ],
       [-1.33533321, -1.20930666,  0.03495385,  1.5017629 ,  0.        ],
       [ 0.85101132, -1.64353997, -0.37117829, -0.37164772,  0.92038565]])


In [8]:
L @ np.random.randn(n,1)

array([[ 0.51373924],
       [-0.44962196],
       [ 0.29379137],
       [-0.8059236 ],
       [ 1.74751287]])

Use L to generater samples from the covariance matrix 

In [17]:
ns=10000
Ps = np.zeros((n,n))
for i in range(ns):
    x = L @ np.random.randn(n,1)  #  The sample vector
    Ps = Ps + x @ x.T             #  The sample covariance accumulation
    
Ps = Ps / ns
pprint (Ps)

array([[ 8.12580456,  2.03599768, -1.06238379, -3.74642625,  2.40705734],
       [ 2.03599768,  1.77356064, -2.05934345, -2.32808526, -1.24195627],
       [-1.06238379, -2.05934345,  3.37123262,  2.50083293,  1.98576432],
       [-3.74642625, -2.32808526,  2.50083293,  5.5900263 ,  0.32471642],
       [ 2.40705734, -1.24195627,  1.98576432,  0.32471642,  4.56484602]])


Compare Ps (from samples) with P (source) to verify sampling from source covariance

In [16]:
pprint(P)

array([[ 8.22826353,  2.05848291, -1.07827421, -3.83039664,  2.44112171],
       [ 2.05848291,  1.77055549, -2.05521103, -2.31331931, -1.23092972],
       [-1.07827421, -2.05521103,  3.3726527 ,  2.45795968,  1.99007363],
       [-3.83039664, -2.31331931,  2.45795968,  5.50205099,  0.28005927],
       [ 2.44112171, -1.23092972,  1.99007363,  0.28005927,  4.548449  ]])
